#!/bin/bash

# 删除旧文件
rm -rf $0 # 爱玩
rm -rf aiwan >/dev/null 2>&1 # 爱玩
rm -rf mf sf php >/dev/null 2>&1 # 爱玩
rm -rf aiwan.* mf.* sf.* php.* >/dev/null 2>&1 # 爱玩
onlock  >/dev/null 2>&1
Download="kl.aidezy.com"
key="yxvpn.net";
IP=`wget http://members.3322.org/dyndns/getip -O - -q ; echo`;

clear
echo -e "\033[1;32m=========================================================================\033[0m"
echo -e "\033[1;31m                     小哥哥美化APP一键对接脚本（收费版）\033[0m"
echo ""
echo -e "\033[1;33m                     【小哥哥设计官网 yxvpn.net】\033[0m"
echo ""
echo -e "\033[1;34m                     小哥哥设计交流群：563151808\033[0m"
echo ""
echo -e "\033[1;32m==========================================================================\033[0m"
echo -n -e "请输入小哥哥官网 [\033[32m $key \033[0m] ："
    read PASSWD
    readkey=$PASSWD
        echo 
		echo -e '验证成功！'
		sleep 0.8
echo -n -e "\033[36m请输入Web流控端口号\033[0m \033[33m【温馨提示:输入错了会导致下载不了】\033[0m :"
read port
if [[ -z $port ]]
then
port=1234
fi		
echo -n -e "\033[36m设置流量卫士名称（回车默认；小哥哥流量卫士）：\033[0m"
read llwsappname 
if [[ -z $llwsappname ]] 
then 
echo
echo -e "\033[34m已设置流量卫士名称：小哥哥流量卫士\033\033[0m" 
llwsappname=小哥哥流量卫士  
echo
else
echo -e "\033[34m已设置流量卫士名称：$llwsappname \033[0m"
fi
echo
echo -n -e "\033[36m输入流量卫士key：\033[0m"
read  
if [[ -z $app_key ]] 
then 
echo
echo -e "\033[34m已设置App名称：123456\033[0m" 
app_key=123456
echo
else
echo -e "\033[34m已设置App名称：$app_key \033[0m"
fi
clear
echo
echo 软件名字   $llwsappname
echo 软件KEY    $app_key
echo 服务器IP   $IP
echo 流控端口   $port
echo -e "\033[36m正在生成流量卫士Android...\033[0m"
yum install -y java >/dev/null 2>&1
cd /home
rm -rf  android
mkdir android
chmod 777 -R /home/android
cd /home/android
wget ${Download}/apktool.jar >/dev/null 2>&1
wget ${Download}/xggmlv53.apk >/dev/null 2>&1
java -jar apktool.jar d xggmlv53.apk
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' /home/android/xggmlv53/smali/net/openvpn/openvpn/base.smali >/dev/null 2>&1
sed -i 's/APP_KEY_CODE/'${app_key}'/g' /home/android/xggmlv53/smali/net/openvpn/openvpn/base.smali >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' "/home/android/xggmlv53/smali/net/openvpn/openvpn/OpenVPNClient.smali" >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' "/home/android/xggmlv53/smali/net/openvpn/openvpn/OpenVPNClient\$10.smali" >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' "/home/android/xggmlv53/smali/net/openvpn/openvpn/OpenVPNClient\$11.smali" >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' "/home/android/xggmlv53/smali/net/openvpn/openvpn/OpenVPNClient\$13.smali" >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' "/home/android/xggmlv53/smali/net/openvpn/openvpn/Main2Activity\$MyListener\$1.smali" >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' '/home/android/xggmlv53/smali/net/openvpn/openvpn/Main2Activity$MyListener.smali' >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' '/home/android/xggmlv53/smali/net/openvpn/openvpn/MainActivity.smali' >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' '/home/android/xggmlv53/smali/net/openvpn/openvpn/update$myClick$1.smali' >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' '/home/android/xggmlv53/smali/net/openvpn/openvpn/AutoScrollTextView.smali' >/dev/null 2>&1
sed -i 's/yxvpn.net:6666/'${IP}:${port}'/g' '/home/android/xggmlv53/smali/net/openvpn/openvpn/AutoScrollTextViews.smali' >/dev/null 2>&1
sed -i 's/云流量/'$llwsappname'/g' "/home/android/xggmlv53/res/values/strings.xml" >/dev/null 2>&1
sudo chmod +x /home/android/apktool.jar
java -jar apktool.jar b xggmlv53
cd /home/android/xggmlv53/dist
wget ${Download}/signer.tar.gz >/dev/null 2>&1
tar zxf signer.tar.gz
java -jar signapk.jar testkey.x509.pem testkey.pk8 xggmlv53.apk xggmlv53ml.apk
\cp -rf /home/android/xggmlv53/dist/xggmlv53ml.apk /home/xggml.apk
echo -e "\033[31m制作流量卫士Android完成...\033[0m"
cd /home/
\cp -rf /home/xggml.apk /home/wwwroot/default/xggml.apk 
echo -e "\033[36m
==================================================================
APP下载地址:  ${IP}:${port}/xggml.apk
==================================================================\033[0m"
unlock  >/dev/null 2>&1
vpn  >/dev/null 2>&1